### ISSUE TITLE
failed to query available provider packages

### ISSUE THREAD

**Issue by wNvSp1r1T** [crossplane-contrib/provider-terraform#110]
connect failed: cannot initialize Terraform configuration: failed to query available provider packages
I'm trying to use ldap-provider  https://github.com/Ouest-France/terraform-provider-ldap

```
apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: example-inline
  annotations:
    crossplane.io/external-name: group
spec:
  forProvider:
    source: Inline
    module: |
      resource "ldap_group" "group" {
        ou          = "OU=test1,OU=test,OU=Resources,OU=Main,DC=test,DC=eu"
        name        = "MyTestTerraformgroup"
        description = "My group description"
      }
  writeConnectionSecretToRef:
    namespace: default
    name: terraform-workspace-example-inline
```

with correct providerconfig.
But cannot get available provider packages even with proxy.

i was saw examples with source: Remote
```
source: Remote
    module: https://github.com/crossplane/tf
```
but I don't understand how to pass parameters correctly like this one:
```
resource "ldap_group" "group" {
        ou          = "OU=test1,OU=test,OU=Resources,OU=Main,DC=test,DC=eu"
        name        = "MyTestTerraformgroup"
        description = "My group description"
      }
```
I will be very grateful for the explanations and tips in solving my problem
