### ISSUE TITLE
AWS ini credentials from secret creates blank file

### ISSUE THREAD

**Issue by rejoshed** [crossplane-contrib/provider-terraform#129]
### What happened?
I created an aws-creds.ini file and turned it into a k8s secret. I then attempted to use it to create an ECS instance.

Unfortunately I get the following status error:
``` json
...
           "lastTransitionTime": "2022-11-09T00:10:23Z",
            "message": "create failed: cannot apply Terraform configuration: creating ec2 instance: unauthorizedoperation: you are not authorized to perform this operation. encoded authorization failure message: hbgzon_jbrgjaaq0_nkv1rsdwvkumeaubxnktgdoiv3dvca2c_h1twi0u0x-2rqqrqs5f7xo5egwrsu2vi_ykna7ywi40ofydvug9rtfsmlytezyosjofw4c3vufvrz8kenj6ipo4nzg6ftfce0jghobmo7qsveiukpg7_hp5wjnvug-dzrh8zs5lelmdptie5wk_l7z9a0q4uf4chfgop55rcp8cz-c37pukx2cja-o-4zfiarzgdwtxiigefqs0ndtht6qibxfty9bwdynirvf4kzef19kze6njcjcviqyi9gqlrzmr_ioeahlbcmuxqwekfskct1pddqx5odvkjcalyaojjizvsr6vce4f6nleodji-v_whza0stukvndt4qn8i6erj6pnysugx0c9nqmlkdgyltgf92yqkakwewiixxl4j475uxndabdvgtd2vjuvq43cw-h2ryqwpn4ckb8cpoutmxfhca9tu5a26cszf8tz27yx7b3olikdq8wqj64xwmqcnwu6jx4jonygfrt_wlbktkburl9p-u8q6pavmqwyl_vfi2rplps9n5icheub2brfruebbbxp6vqobvduab_c1wertowbvzpfps4rz10veqbekpkqyfecba7k--usgcm48rlr_5z8o_ujtk1iwce6nkvajuy9mbwzhu_d5awveluwsdjecuccl18oitr",
            "reason": "ReconcileError",
            "status": "False",
            "type": "Synced"
...
```

From here I tried to decode the authorization error, but the AWS cli claims the error is corrupted.

I'm guessing this is to do with provider-terraform error handling in some way.

Oh well I thought, and I `kubectl exec -it` ed into the provider pod.

I then checked into the created aws-creds.ini file and it was empty.

1). Is it possible to better handle the error output so I could decode it?
2). Why is the aws-creds.ini file empty on the provider? I thought maybe it was a placeholder or something, but that doesn't really make sense to me. I'm guessing this is the reason I'm getting the auth error to begin with.

Thank you!!! 

### How can we reproduce it?
`kubectl -n crossplane-system create secret generic aws-creds --from-file=./aws-creds.ini`

My AWS provider config is:
``` yaml
apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: aws-us-west-2
spec:
  credentials:
  - filename: aws-creds.ini
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: credentials
  configuration: |
      terraform {
        backend "kubernetes" {
          secret_suffix     = "providerconfig-aws-us-west-2"
          namespace         = "crossplane-system"
          in_cluster_config = true
        }
      }
      provider "aws" {
        shared_credentials_files = ["aws-creds.ini"]
        region  = "us-west-2"
      }
```

and then I created the following `workspace`

``` yaml
apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: aws-us-west-2
spec:
  credentials:
  - filename: aws-creds.ini
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: credentials
  configuration: |
      terraform {
        backend "kubernetes" {
          secret_suffix     = "providerconfig-aws-us-west-2"
          namespace         = "crossplane-system"
          in_cluster_config = true
        }
      }
      provider "aws" {
        shared_credentials_files = ["aws-creds.ini"]
        region  = "us-west-2"
      }
```

### What environment did it happen in?
Crossplane version: crossplane/crossplane:v1.9.0

Running on EKS.
K8s 1.21
OS on client is Mac M1
