### ISSUE TITLE
Requesting a helm chart wrapper for `kind: Workspace`

### ISSUE THREAD

**Issue by nitrocode** [crossplane-contrib/provider-terraform#132]
### What problem are you facing?

I'd like a generic chart, without having to roll my own, to deploy remote terraform module using different inputs.

For example, I'd like to deploy a `terraform` directory across our services across different repos.

```
org/titan-service
org/atlantis-service
org/icecube-service
```

### How could Crossplane help solve your problem?

Chart template example (this isn't best practices but just serves as a very basic example to illustrate this feature request)

```yaml
apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: {{ .Values.name }}
spec:
  forProvider:
    source: Remote
    module: "{{ .Values.source }}"
  writeConnectionSecretToRef:
    namespace: {{ .Values.namespace }}
    name: {{ .Values.name }}
```

Then

```sh
helm repo add crossplane-terraform-remote-module https://charts.crossplane.io/master/
```

i.e.

```sh
helm install <gh-org>-<gh-repo>-<gh-project> crossplane-terraform-remote-module \
  --set "name=titan" \
  --set "namespace=crossplane" \
  --set "source=git::https://<gh-user>:<gh-password>@github.com/<gh-org>/<gh-repo>.git//terraform"
```
