### ISSUE TITLE
Support of git credentials store for private remote modules checkout

### ISSUE THREAD

**Issue by ytsarev** [crossplane-contrib/provider-terraform#21]
### What problem are you facing?

Currently, the only way to checkout the remote module from private git repo looks like
```yaml
  forProvider:
    source: Remote
    module: "git::https://<user>:<token>@github.com/org/repo//module/path
``` 
which is obviously insecure as the git credentials are residing in Workspace spec as plain text

### How could Crossplane help solve your problem?

Adding support of https://git-scm.com/docs/git-credential-store and providing git credentials as a Secret would solve it.

A similar approach to https://github.com/AbsaOSS/terraform-controller/commit/c51fea0c1c3887bea1b45a1a0b5f68bb44cd1c56 can be used
