### ISSUE TITLE
Provide inline `vars` as object instead of list

### ISSUE THREAD

**Issue by ytsarev** [crossplane-contrib/provider-terraform#22]
### What problem are you facing?
Currently, inline vars are provided as a list of key/value pairs

```yaml
            vars:
              - key: application
                value: to-be-patched
              - key: app_id
                value: to-be-patched
```

So they can be patched within a Composition only through the index:

```yaml
     patches:
        - fromFieldPath: "spec.parameters.Application"
          toFieldPath: "spec.forProvider.vars[0].value"
        - fromFieldPath: "spec.parameters.AppId"
          toFieldPath: "spec.forProvider.vars[1].value"
```

It quickly becomes inconvenient and brittle to maintain when the number of variables to patch grows

### How could Crossplane help solve your problem?

A possible solution would be to provide `vars` as an object so it would look like

```yaml
            vars:
              application: to-be-patched
              app_id: to-be-patched
```
and it would be easy to patch it within a Composition by a direct key reference:
```yaml
     patches:
        - fromFieldPath: "spec.parameters.Application"
          toFieldPath: "spec.forProvider.vars.application"
        - fromFieldPath: "spec.parameters.AppId"
          toFieldPath: "spec.forProvider.vars.app_id"
```
The existing provider-aws part where I've seen the similar approach https://doc.crds.dev/github.com/crossplane/provider-aws/eks.aws.crossplane.io/Cluster/v1beta1@v0.20.0#spec-forProvider-tags
