### ISSUE TITLE
Unable to use private repo's in workspace-remote module in terraform.

### ISSUE THREAD

**Issue by arun12cool** [crossplane-contrib/provider-terraform#34]
### What happened?

```
tf-remote.yaml :

---
apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: arun-cp-test-remote-1
  annotations:
spec:
  forProvider:
    source: Remote
    module: git::https://github.tools.io/arun12cool/tf.git//tf?ref=main
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: terraform-workspace-arun-cp-remote-1
  providerConfigRef:
    name: tfcon
--
```

```
Error : 
Warning CannotConnectToProvider 3m33s (x21 over 75m) managed/workspace.tf.crossplane.io (combined from similar events): cannot get remote Terraform module: error downloading 'https://github.tools.io/arun12cool/tf.git//tf?ref=main': /usr/bin/git exited with 128: Cloning into '/tmp/getter992332245/temp'...
fatal: unable to access 'https://github.tools.io/arun12cool/tf.git/': Failed to connect to github.tools.io port 443: Operation timed out
```

### How can we reproduce it?

Please use a private repo URL to reproduce the same.

### What environment did it happen in?
Crossplane version:  v1.6.3
**Package used :**
crossplane/provider-aws:alpha
crossplane/provider-terraform:master

Include at least the version or commit of Crossplane you were running. Consider
also including your:

* Cloud provider or hardware configuration.     :  AWS  EKS Cluster
* Kubernetes version (use `kubectl version`) : 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.15-eks-9c63c4", GitCommit:"9c63c4037a56f9cad887ee76d55142abd4155179", GitTreeState:"clean", BuildDate:"2021-10-20T00:21:03Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) : EKS - AWS
* OS (e.g. from /etc/os-release)  : MAC 
* Kernel (e.g. `uname -a`) : Darwin GC02XD0C8JG5HE 19.6.0 Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64 x86_64
