### ISSUE TITLE
Unable to create resource using Inline source

### ISSUE THREAD

**Issue by sharigitpersonal** [crossplane-contrib/provider-terraform#37]
### What happened?

Trying to import terraform module to crossplane. 

Package installed : crossplane/provider-terraform:master

ProviderConfig looks like below:

```
apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: aws
spec:
  credentials:
    - secretRef:
        namespace: crossplane-system
        name: aws-creds
        key: creds
      source: Secret
      filename: aws-creds.json
```

AWS providerconfig is as below:
```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default 
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds
```

Resource.yaml looks like this.

```
apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: s3bucket
  annotations: 
    crossplane.io/external-name: tfbucket
spec:
  forProvider:
    source: Inline
    module: |
      resource "aws_s3_bucket" "b" {
        bucket = "my-tf-test-bucket"
        tags = {
          Name        = "crossplane"
          Environment = "Demo"
        }
      }

      resource "aws_s3_bucket_acl" "example" {
        bucket = aws_s3_bucket.b.id
        acl    = "private"
      }
     
      output "url" {
              value = aws_s3_bucket.b.id
      }
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: tfinline
  providerConfigRef: 
    name: aws
```
When I do a kubectl apply : I am getting the below error 

    Message:               observe failed: **cannot list Terraform resources: no state file was found!**
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                         Age                   From                                Message
  ----     ------                         ----                  ----                                -------
  Warning  CannotObserveExternalResource  35s (x10 over 5m11s)  **managed/workspace.tf.crossplane.io  cannot list Terraform resources: no state file was found!**

Can you please tell , if there are any errors ? 
I am able to create resources through crossplane native providers. But not through this, it would really great if you can help on this.

### What environment did it happen in?
Crossplane version: crossplane/crossplane:v1.6.4

**Comment by bobh66** [comment]
@sharigitpersonal I believe your Terraform module needs a terraform block to configure the backend:

```
terraform {
        backend "kubernetes" {
          secret_suffix     = "xp"
          namespace         = "default"
          in_cluster_config = true
        }
      }
```

and you may need to configure the Terraform aws provider region:

```
provider "aws" {
              region = "%s"
            }
```

Hope this helps

**Comment by sharigitpersonal** [comment]
@bobh66  , Thanks for your help. I tried it .

The new yaml looks like this 


```
apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: s3bucketnew
spec:
  forProvider:
    source: Inline
    module: |
      resource "aws_s3_bucket" "b" {
        bucket = "testcrossplane"
        tags = {
          Name        = "crossplane"
          Environment = "Demo"
        }
      }

      resource "aws_s3_bucket_acl" "example" {
        bucket = aws_s3_bucket.b.id
        acl    = "private"
      }

      output "url" {
              value = aws_s3_bucket.b.id
      }

      provider "default" {
              region = "ca-central-1"
                    version = "4.8.0"
              }
      
      terraform {
            backend "kubernetes" {
                secret_suffix = "xp"
                namespace      = "crossplane-system"
                in_cluster_config = "true"
           }
      }
  providerConfigRef:
    name: default
```
the providerconfig yaml looks like this 

```
apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default 
spec:
  credentials:
    - secretRef:
        namespace: crossplane-system
        name: aws-creds
        key: creds
      source: Secret
      filename: aws-creds.conf  
```

Error I am getting is 

```
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2022-03-28T12:24:07Z
    Message:               connect failed: cannot initialize Terraform configuration: failed to query available provider packages
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                   Age              From                                Message
  ----     ------                   ----             ----                                -------
  Warning  CannotConnectToProvider  1s (x2 over 6s)  managed/workspace.tf.crossplane.io  cannot initialize Terraform configuration: failed to query available provider packages
```

kubectl get pkg shows 👍 

```
NAME                                                          INSTALLED   HEALTHY   PACKAGE                                                  AGE
configuration.pkg.crossplane.io/xp-getting-started-with-aws   True        True      registry.upbound.io/xp/getting-started-with-aws:v1.6.4   6d4h

NAME                                                       INSTALLED   HEALTHY   PACKAGE                                AGE
provider.pkg.crossplane.io/crossplane-provider-aws         True        True      crossplane/provider-aws:v0.25.0        6d4h
provider.pkg.crossplane.io/crossplane-provider-jet-aws     True        True      crossplane/provider-jet-aws:v0.4.2     3d19h
provider.pkg.crossplane.io/crossplane-provider-terraform   True        True      crossplane/provider-terraform:master   3d6h
```

Can you please shed some light on this ?
