### ISSUE TITLE
Handle tf state lock during the controller pod restart/upgrade

### ISSUE THREAD

**Issue by ytsarev** [crossplane-contrib/provider-terraform#46]
### What problem are you facing?

There can be situations when the controller pod is getting restarted, for example during the provider upgrade process.
Depending on the moment of time it can lead to the state lock and Workspace MR malfunction within the new pod
```
    - lastTransitionTime: "2022-04-07T08:57:04Z"
      message: 'observe failed: cannot diff (i.e. plan) Terraform configuration: error
        acquiring the state lock'
      reason: ReconcileError
      status: "False"
      type: Synced
```
### How could Crossplane help solve your problem?

We need to find a way to gracefully handle lock release mechanism in case of controller pod recreation.

**Comment by bobh66** [comment]
@ytsarev I'm seeing this same problem with stuck Lease object holderIdentity values.

Maybe something  like this:
```
lifecycle:
    preStop:
      exec:
        command: ["/bin/sh","-c","while killall -HUP terraform; do sleep 1; done"]
```

I'm going to add it to my ControllerConfig and see if it has any impact, but it will probably take a few days to be confident if it does resolve the problem.
