### ISSUE TITLE
Configuring Gitlab Terraform Provider

### ISSUE THREAD

**Issue by ChrisJBurns** [crossplane-contrib/provider-terraform#59]
### What happened?
I am trying to use the `gitlabhq/gitlab` terraform provider, but it's not working properly. Possibly configuration isn't right?

### How can we reproduce it?
Configure the terraform provider like so, with the `gitlab` provider plugin.
```yaml
---
apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  # Note that unlike most provider configs this one supports an array of
  # credentials. This is because each Terraform workspace uses a single
  # Crossplane provider config, but could use multiple Terraform providers each
  # with their own credentials.
  credentials:
  - filename: gitlab-token
    source: Secret
    secretRef:
      namespace: crossplane
      name: gitlab-token
      key: token
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  configuration: |
      provider "gitlabhq/gitlab" {
        token = "gitlab-token"
      }

      terraform {
        backend "kubernetes" {
          secret_suffix     = "providerconfig-default"
          namespace         = "crossplane"
          in_cluster_config = true
        }
      }
```

And then try to create a deploy key like so
```yaml
    - name: create-deploy-key
      base:
        apiVersion: tf.crossplane.io/v1alpha1
        kind: Workspace
        metadata:
          name: create-deploy-key
          annotations:
            crossplane.io/external-name: create-deploy-key
        spec:
          forProvider:
            source: Inline
            module: |

              variable "deploy_key" {
                type = string
              }

              data "gitlab_project" "flux_config_for_apps_cluster" {
                id = "REPO_URL"
              }

              resource "gitlab_deploy_key" "flux_apps_cluster_deploy_key" {
                title   = "Flux Apps Cluster Deploy Key - Crossplane"
                project = data.gitlab_project.flux_config_for_apps_cluster.id
                key     = var.deploy_key
                can_push = true

                depends_on = [data.gitlab_project.flux_config_for_apps_cluster]
              }

              resource "gitlab_deploy_key_enable" "flux_admin_cluster_deploy_key_enable" {
                project = data.gitlab_project.flux_config_for_apps_cluster.id
                key_id  = gitlab_deploy_key.flux_apps_cluster_deploy_key.id
              }
            vars:
              - deploy_key
          writeConnectionSecretToRef:
            namespace: crossplane
            name: terraform-workspace-example-inline
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: status.publicKey
          toFieldPath: spec.forProvider.vars[0].value"
          transforms:
            - type: string
              string:
                type: Convert
                convert: ToBase64
```

### What environment did it happen in?
Crossplane version: 
1.8.1
AKS
K8s version: 1.22

**Comment by ChrisJBurns** [comment]
I have managed to get a Deploy Key to exist using the following config.

```yaml
---
apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  # Note that unlike most provider configs this one supports an array of
  # credentials. This is because each Terraform workspace uses a single
  # Crossplane provider config, but could use multiple Terraform providers each
  # with their own credentials.
  credentials:
  - filename: gitlab-token
    source: Secret
    secretRef:
      namespace: crossplane
      name: gitlab-token
      key: token
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  configuration: |
      terraform {
        required_providers {
          gitlab = {
            source = "gitlabhq/gitlab"
            version = "3.15.0"
          }
        }
      }

      provider "gitlab" {
        token = "API_KEY"
      }

      terraform {
        backend "kubernetes" {
          secret_suffix     = "providerconfig-default"
          namespace         = "crossplane"
          in_cluster_config = true
        }
      }
```

But as illustrated above, I've had to hardcode my API key. I can't seem to pass it via a secret like the GCP examples (perhaps this is because it's a file only for that example).

Additionally, although it's created the Deploy Key, the logs are constantly saying that there's a 404 not found when looking for the Deploy Key (even though it's definitely created). Lastly, I've noticed that the resource isn't tracked via Crossplane and can't see any trace of it when doing `kubectl get managed`. This would also explain why, when I remove the resource from the composition, the Deploy Key isn't removed as well.
