### ISSUE TITLE
Allow workspaces to use multiple Terraform providers

### ISSUE THREAD

**Issue by negz** [crossplane-contrib/provider-terraform#7]
### What problem are you facing?

Currently this provider takes a fairly simple and limited view of provider credentials. A single key can be read from a secret and will be written to a well known file path - `./credentials` - relative to `main.tf`. This effectively limits Terraform workspaces to using a single (Terraform) provider. It also requires the author to write the `provider` block in HCL to consume said credentials.

### How could Crossplane help solve your problem?

We need to remain pretty open ended here to increase the chances that we'll be compatible with existing Terraform configurations. We may however be able to add an 'automatic' mode to the `ProviderConfig` though. For example:

```yaml
apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  # We support an array of credentials. Each is written to the supplied filename
  # relative to the configuration's main.tf file.
  credentials:
  - filename: credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-credentials
      key: credentials
  # An optional block of "provider config scoped" configuration that is injected
  # into every workspace that uses this provider config. This configuration is
  # written to ./crossplane-providerconfig.tf relative to the main.tf file.
  configuration: |
      provider "google" {
        credentials = "credentials"
        project     = "crossplane-example-tf"
      }
```
