### ISSUE TITLE
Does not seem to work with IAM roles for service accounts

### ISSUE THREAD

**Issue by andrewhibbert** [crossplane-contrib/provider-terraform#70]
### What happened?

Get the following error:

```
 Warning  CannotObserveExternalResource  6s (x7 over 103s)     managed/workspace.tf.crossplane.io  cannot diff (i.e. plan) Terraform configuration: error configuring terraform aws provider: no valid credential sources for terraform aws provider found.
```

### How can we reproduce it?

Set the controller config to the following:
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: terraform-config
  labels:
    app: crossplane-provider-terraform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account>:role/<rolename>
spec:
  podSecurityContext:
    fsGroup: 2000
  image: crossplane/provider-terraform-controller:v0.2.0
  args: ["-d"]
```
Can see the annotation however the terraform aws provider does not seem to use it

### What environment did it happen in?
Crossplane version: 
1.8

**Comment by bobh66** [comment]
@andrewhibbert - do you have the role configured with a trust relationship for the Service Account and OIDC provider as described here:

https://github.com/crossplane-contrib/provider-aws/blob/master/AUTHENTICATION.md#using-iam-roles-for-serviceaccounts

We have this working in our environment so I know it's supported - or at least functional.

**Comment by luisdavim** [comment]
@bobh66 you have role based auth working with the Terraform provider? I know it works with the AWS provider, but is this supported by the Terraform provider?
Can you share an example terraform provider config?

**Comment by luisdavim** [comment]
When we set the SA annotations with the AWS role, there's a controller that injects some env vars into the pod, like for example, with the AWS provider we get:

```console
$ kdpo provider-aws-600a696e071d-8444cb57d4-pkhhl -n crossplane-system | gr 'AWS_'
      AWS_DEFAULT_REGION:           us-west-2
      AWS_REGION:                   us-west-2
      AWS_ROLE_ARN:                 arn:aws:iam::000000000:role/eks-cluster-name
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

maybe we can use something like:

```tf
provider "aws" {
  assume_role {
    role_arn                = "$AWS_ROLE_ARN"
    session_name            = "SESSION_NAME"
    web_identity_token_file = "$AWS_WEB_IDENTITY_TOKEN_FILE"
  }
}
```

to get the TF provider to use that role, is it something like this that you used @bobh66 ?

**Comment by bobh66** [comment]
@luisdavim We put the same type of role annotation on the controllerconfig for terraform so the pod picks up the native AWS ENV and credentials:

```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::accountid:role/provider-terraform
```

which allows the terraform aws provider to use the default set of credentials.   Then when we need the aws provider to use a different account we can use the assume_role configuration.

**Comment by luisdavim** [comment]
I tried that and I get the following error:

```
cannot get credentials: no extraction handler registered for source: InjectedIdentity
```

Adding the annotation worked as I can see the `AWS_` envs vars injected into the terraform provider pod, but is there something else to it? In the `ProviderConfig` I'm setting the credentials to:

```yaml
credentials:
  - filename: aws-creds.ini
    source: InjectedIdentity
```

**Comment by luisdavim** [comment]
This seems to be the method the provider uses: https://github.com/crossplane/crossplane-runtime/blob/master/pkg/resource/providerconfig.go#L89-L102 it doesn't contain a `case` for `xpv1. CredentialsSourceInjectedIdentity`

**Comment by bobh66** [comment]
My default providerconfig has:

```
  spec:
    credentials:
    - filename: aws.json
      source: None
```

**Comment by luisdavim** [comment]
For me, that fails with:

```
cannot diff (i.e. plan) Terraform configuration: error configuring terraform aws provider: no valid credential sources for terraform aws provider found.
```

**Comment by luisdavim** [comment]
According to the TF docs that should work:

> If you're running Terraform on EKS and have configured [IAM Roles for Service Accounts (IRSA)](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), Terraform can use the pod's role. This support is based on the underlying AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE environment variables being automatically set by Kubernetes or manually for advanced usage.

And the vars are there for sure:

```console
$ kex -n crossplane-system provider-terraform-6f2df84a9c2f-965bf8564-c72bb -- env | grep AWS_
AWS_DEFAULT_REGION=us-west-2
AWS_REGION=us-west-2
AWS_ROLE_ARN=arn:aws:iam::0000000:role/role-name
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

**Comment by luisdavim** [comment]
Is there a way to inject extra env vars? Do we need to set `AWS_SDK_LOAD_CONFIG=1` ?

**Comment by bobh66** [comment]
I think you also need pooSecurityContext.fsGroup: 2000 in the controller config to allow access to the filesystem credentials:

```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: terraform
spec:
  args:
  - --debug
  podSecurityContext:
    fsGroup: 2000
```

**Comment by luisdavim** [comment]
That didn't work either, I'll keep looking into it, thanks for the help.

This is how the pod looks like ATM:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  generateName: provider-terraform-6f2df84a9c2f-5c4876dc6d-
  labels:
    pkg.crossplane.io/provider: provider-terraform
    pkg.crossplane.io/revision: provider-terraform-6f2df84a9c2f
    pod-template-hash: 5c4876dc6d
  name: provider-terraform-6f2df84a9c2f-5c4876dc6d-g8lhd
  namespace: crossplane-system
spec:
  containers:
    - args:
        - --debug
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: AWS_SDK_LOAD_CONFIG
          value: "1"
        - name: AWS_DEFAULT_REGION
          value: us-west-2
        - name: AWS_REGION
          value: us-west-2
        - name: AWS_ROLE_ARN
          value: arn:aws:iam::000000000:role/role-name
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
      image: crossplane/provider-terraform-controller:v0.2.0
      imagePullPolicy: IfNotPresent
      name: provider-terraform
      ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: provider-terraform-6f2df84a9c2f-token-slgl9
          readOnly: true
        - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
          name: aws-iam-token
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-0-161-181.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 2000
  serviceAccount: provider-terraform-6f2df84a9c2f
  serviceAccountName: provider-terraform-6f2df84a9c2f
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: aws-iam-token
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              audience: sts.amazonaws.com
              expirationSeconds: 86400
              path: token
    - name: provider-terraform-6f2df84a9c2f-token-slgl9
      secret:
        defaultMode: 420
        secretName: provider-terraform-6f2df84a9c2f-token-slgl9
```
