### ISSUE TITLE
What is the best way to debug errors reported by Terraform?

### ISSUE THREAD

**Issue by nagyv** [crossplane-contrib/provider-terraform#79]
### What happened?

I have a remote module. Once I add the `terraform` and `provider` blocks to it and grab the `secretRef` that I want to use to configure the provider, the module works locally. At the same time, it gives `cannot diff (i.e. plan) Terraform configuration: argument or block definition required` error. 

I already searched for the error, and as the module works locally, I can't debug it any further.

Would you have any suggestions to debug a Terraform run? 

Would you be interested in adding support to various `TF_` environment variables (similar to https://github.com/crossplane-contrib/provider-terraform/issues/69), including the variables documented under https://www.terraform.io/internals/debugging ?

### How can we reproduce it?

ProviderConfig

```yaml
---
apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: terraform-provider
spec:
  credentials:
  - filename: linode-config.ini
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: linode-config
      key: credentials
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: creds
  configuration: |
    terraform {
      required_providers {
        linode = {
          source  = "linode/linode"
          version = "~> 1.28.1"
        }
        postgresql = {
          source  = "cyrilgdn/postgresql"
          version = "~> 1.16.0"
        }
      }
      backend "kubernetes" {
        secret_suffix    = "crossplane"
        in_cluster_config = true
        namespace = "crossplane-system"
      }
    }
    provider "linode" {
      config_path = "linode-config.ini"
    }
```

Workspace (already assumes a postgres instance)

```yaml
apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: pdt-db
spec:
  forProvider:
    source: Remote
    module: git::https://gitlab.com/nagyv/infra.git//cluster/modules/postgres-database?ref=postgres-db-v1.0.4
    vars:
    - key: database_name
      value: pdt-staging
    varFiles:
      - source: SecretKey
        secretKeyRef:
          namespace: crossplane-system
          name: my-postgres-creds
          key: linode-postgres-tfvar-json
        format: JSON
  providerConfigRef:
    name: terraform-provider
  writeConnectionSecretToRef:
    namespace: product-discovery-tool
    name: pdt-db-creds
```

The module code can be found at https://gist.github.com/nagyv/30f9e92dd2fb2abddc05998f5fdec417

### What environment did it happen in?

Crossplane version: 1.9.0
Kubernetes: Linode Kubernetes Engine v1.23
